function PolszamJSCQs(alakok, melyikalak, htmlfajlnev, jsfajlnev, htmltitle) 
% alakok: a PolszamgyakQuizPeldak outputja
% melyikalak:   1: ha szorzattáalakítás a feladat 
%               2: ha zárójelfelbontás a feladat

if melyikalak == 1 
    kerdesek = alakok{1};
    valaszokok = alakok{2};
else
    kerdesek = alakok{2};
    valaszokok = alakok{1};    
end

Betet = '';
 for k = 1:size(kerdesek,2)
    kerdes = kerdesek{1,k};
    % megkeresi az els? üreset
    l = 1;
    while ~isempty(valaszokok{l,k}) && l~=10
        l = l+1;
    end
    valaszok = {valaszokok{1,k}, ...
                valaszokok{2,k}, ...
                valaszokok{3,k}, ...
                valaszokok{4,k}, ...
                valaszokok{5,k}, ...
                valaszokok{6,k}, ...
                valaszokok{7,k}, ...
                valaszokok{8,k}, ...
                valaszokok{9,k}, ...
                valaszokok{10,k} };
    valaszok = valaszok(1:l-1);
    keveres = randperm(length(valaszok));
    helyesvalasz = find(keveres==1);
    kevertvalaszok = valaszok(keveres);
    BetetSor = ['["\\( ', kerdes, '= \\)", ', num2str(helyesvalasz), ',', char(10)];
    for m = 1:l-1
        if m == l-1;
            BetetSor = [BetetSor , '"\\( ', kevertvalaszok{m}, ' \\)"],', char(10)];
        else 
            BetetSor = [BetetSor , '"\\( ', kevertvalaszok{m}, ' \\)",', char(10)];            
        end
    end
    Betet = [Betet, BetetSor];
 end
 
Quiz = ['var Quiz = [', char(10), Betet,'];'];
%Quiz = strrep(Quiz, ['"\\(  \\)",'], '');
%Quiz = strrep(Quiz, ['"\\(  \\)"'], '');
dlmwrite(jsfajlnev, Quiz, '');
fprintf(['... JavaScript kerdeslista kiírva...', char(10)]) 

%Kikérdez? html megírása
HtmlHead=['<head>', char(10), ...
 ' <link rel="SHORTCUT ICON" href="/~attila/logo.png">', char(10), ...
 ' <meta content="text/html; charset=UTF-8" http-equiv="content-type">', char(10), ...
 ' <link rel="stylesheet" type="text/css" href="http://phil.elte.hu/~attila/honlapst.css">', char(10), ...
 ' <title>', htmltitle, '</title> ', char(10), ...
 ' <script ', char(10), ...
 '  type="text/javascript" ', char(10), ...
 '  src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=default"> ', char(10), ...
 ' </script>', char(10), ...
 '</head>'];

HtmlBody=[ ...
'<body background="">', char(10), ...
'<table width = 100% align = center border=0 cellspacing=0 >', char(10), ...
' <tr>', char(10), ...
'  <td colspan=3 >', char(10), ...
'   <table width=100% border=0>', char(10), ...
'    <tr>', char(10), ...
'     <td align=right valign=bottom>', char(10), ...
'      <h3>', char(10), ...
'       e-mail: molnar.h.attila@gmail.com ', char(10), ...
'      </h3>', char(10), ...
'	  </td>', char(10), ...
'	 </tr>', char(10), ...
'   </table>', char(10), ...
'  </td>', char(10), ...
' </tr>', char(10), ...
' <tr>', char(10), ...
'  <td width=20% >', char(10), ...
'   <table width=100% border=0>', char(10), ...
'   </table>', char(10), ...
'  </td>', char(10), ...
'  <td width=80% rowspan=8 align = left valign= top >', char(10), ...
'   <table border=0 valign= top cellpadding=20 width=100%>', char(10), ...
'    <tr>', char(10), ...
'     <td>', char(10), ...
'      <font face="Arial, Helvetica, sans-serif" font color=#666666 size=3>', char(10), ...
'       <form>', char(10), ...
'		<div>', char(10), ...
'		 <h3>', htmltitle , char(10), ...
'	      <br>', char(10), ...
'		  <br>number of questions: <label id="NumberOfQuestions">default</label>', char(10), ...
'        </h3>', char(10), ...
'		</div>', char(10), ...
'	    <button type="button" onclick="PrevQuestion()">previous</button>', char(10), ...
'	    <button type="button" onclick="NextQuestion()">next</button>', char(10), ...
'	    <button type="button" onclick="RndQuestion()">random</button>', char(10), ...
'		<br>', char(10), ...
'		<br>', char(10), ...
'	    <div>', char(10), ...
'		 Q<label id="QuestionNumber">Question number</label>: <label id="QuestionText">The Question will be here</label>', char(10), ...
'		</div>', char(10), ...
'		<br><br>', char(10), ...
'       <div id="Answers">', char(10), ...
'		 The answers will be here', char(10), ...
'		</div>', char(10), ...
'	    <button type="button" onclick="GiveFeedback()">submit</button>', char(10), ...
'		<h3>your answer is <label id="Feedback">...</label></h3>', char(10), ...
'		<div id="ErrorDiv">', char(10), ...
'		</div>', char(10), ...
'	   </form>', char(10), ...
'      </font>', char(10), ...
'     </td>', char(10), ...
'    </tr>', char(10), ...
'   </table>', char(10), ...
'  </td>', char(10), ...
' </tr>', char(10), ...
'</table>', char(10), ...
'</body>'];

HtmlScriptSection=[ ...
    '<script src="', jsfajlnev, '"></script>', char(10), ...
'<script type="text/x-mathjax-config">MathJax.Hub.Config({ TeX: { extensions: ["AMSmath.js", "AMSsymbols.js"]}});</script>', char(10), ...
'<script>', char(10), ...
'var Qnum = 0', char(10), ...
'var AnswerCardinality = Quiz[Qnum].length-2;', char(10), ...
char(10), ...
'function WriteQuestion()', char(10), ...
'{var AnswerText ='''';', char(10), ...
' document.getElementById("QuestionNumber").innerHTML = Qnum+1;', char(10), ...
' document.getElementById("QuestionText").innerHTML = Quiz[Qnum][0];', char(10), ...
' for (var i=0;i<AnswerCardinality;i++)', char(10), ...
'  {AnswerText = AnswerText + ''<input type="radio" name="Answer" id="Answer_''+i+''" value="Value_''+i+''" onclick="DeleteFeedback()"/>'' + Quiz[Qnum][i+2] + ''<br><br>'';}', char(10), ...
' document.getElementById("Answers").innerHTML = AnswerText;', char(10), ...
' MathJax.Hub.Queue(["Typeset",MathJax.Hub]);}', char(10), ...
' ', char(10), ...
'function GiveFeedback()', char(10), ...
'{var pipalvavan=0;', char(10), ...
' for (var i=0;i<AnswerCardinality;i++){if (document.getElementById("Answer_"+i).checked) {pipalvavan = i+1;};}', char(10), ...
' if (pipalvavan==Quiz[Qnum][1]) {document.getElementById("Feedback").innerHTML = "<font color=lime>Right!</font>";}', char(10), ...
'  else if (pipalvavan==0)', char(10), ...
'          {document.getElementById("Feedback").innerHTML = "<font color=blue>waiting for your choice</font>";}', char(10), ...
'          else {document.getElementById("Feedback").innerHTML = "<font color=red>Wrong.</font>";}}', char(10), ...
char(10), ...
'function DeleteFeedback(){document.getElementById("Feedback").innerHTML = "<font color=blue>...</font>";}', char(10), ...
char(10), ...
'function NextQuestion()', char(10), ...
'{if (Qnum==Quiz.length-1) {Qnum = 0;} else { Qnum = Qnum +1;}', char(10), ...
' AnswerCardinality = Quiz[Qnum].length-2;', char(10), ...
' WriteQuestion();', char(10), ...
' DeleteFeedback();}', char(10), ...
char(10), ...
'function PrevQuestion()', char(10), ...
'{if (Qnum==0) {Qnum = Quiz.length-1;} else { Qnum = Qnum -1;}', char(10), ...
' AnswerCardinality = Quiz[Qnum].length-2;', char(10), ...
' WriteQuestion();', char(10), ...
' MathJax.Hub.Queue(["Typeset",MathJax.Hub,"AnswerText1"]);', char(10), ...
' DeleteFeedback();}', char(10), ...
char(10), ...
'function RndQuestion()', char(10), ...
'{var i ', char(10), ...
' do {i= Math.floor(Math.random() * (Quiz.length));}', char(10), ...
' while (i==Qnum) ', char(10), ...
' Qnum = i;', char(10), ...
' AnswerCardinality = Quiz[Qnum].length-2;', char(10), ...
' WriteQuestion();', char(10), ...
' DeleteFeedback();}', char(10), ...
char(10), ...
'WriteQuestion();', char(10), ...
' document.getElementById("NumberOfQuestions").innerHTML = Quiz.length;', char(10), ...
'</script>'];


HTMLfile=['<html>', char(10), ...
            HtmlHead, char(10), ...
            HtmlBody, char(10), ...
            HtmlScriptSection, char(10), ...
          '</html>'];

dlmwrite(htmlfajlnev, HTMLfile, 'delimiter', '');
fprintf(['... Quiz html kiírva...', char(10)]) 

end